### ISSUE TITLE
Material page - Layout

### ISSUE THREAD

**Issue by Nazeeefa** [fairtracks/fairtracks.net#12]
To-do:

- [x] Reduce space between cards
- [x] Remove white space by keeping description concise.
- [x] Remove sub-sections
- [x] Instead, add tags/labels on each card to categorise publication, poster, and presentations.
- [x] Name change; replace 'Media' with 'Blog Post' on Materials page.
- [x] Make sure published date text and button are aligned ("in same row/column") 
- [x] 'TrackFind' poster; mention conference name and date in description. Note: publication dates for poster are not required, we can instead mention 'Presented on <date>'
- [x] Add description for 'TrackFind' poster from Gundersen _*et al*_.
- [x] Add buttons for each material type at the top (above cards); that allows user to filter for relevant content. Button colours would be based on colour scheme used throughout webpages. This should be implemented when material has a lot of information. It is not required at the moment.

**Comment by Nazeeefa** [comment]
Given current/latest layout, I don't think drop-down for 'Materials' section (in top menu) is so important any longer. One page is more than enough as it has all the information :)

**Comment by Nazeeefa** [comment]
Given current/latest layout and the idea about buttons (point 5 mentioned above), I don't think drop-down for 'Materials' section (in top menu) is so important any longer. One page is more than enough as it has all the information :)

**Comment by Nazeeefa** [comment]
Given current/latest layout and the idea about buttons (mentioned above), I don't think drop-down for 'Materials' section (in top menu) is so important any longer. One page is more than enough as it has all the information :)

**Comment by Nazeeefa** [comment]
To-do:

- [x] Create materials2 page to implement 'News' design
- [x] Add a couple of 'News' cards
- [x] Rename categories, according to 'Materials' categories
- [ ] Add/check functionality that brings Categories card/feature into view while a user is scrolling; note, this is more useful and relevant for a large amount of content.
- [x] Clicking on a 'Category' does not only filter for corresponding 'Material', but also displays items in reverse/inverse chronological ordering i.e. most recent is listed first.
- [ ] Add following tags (note: this is separate from categories); software, and FAIRtracks

**Comment by joshbaskaran** [comment]
I am yet to add the floating/scrolling menu and the general style of each of the cards/UI can really use some love here but functionally I have the filter working.

**Comment by Nazeeefa** [comment]
- [x] Remove checklist feature
- [x] Add 'View all' option?
- [x] Add tags
- [x] Make space for text for publication date, to be able to add e.g. Published/Presented on DD-MM-YYYY
- [x] Make space for text required as pointer for external link e.g. Read full article, Read the full poster [PDF format], Watch the full webinar, etc.
- [x] Add banner colour corresponding to the card category.

**Comment by joshbaskaran** [comment]
Note regarding the 'view all', for tags, I'm making it so that when nothing is selected, it behaves as if everything is. I feel this offers a better UX.

I really don't like the colours here, so if someone can figure out what would look nice here, I would appreciate it.
