### ISSUE TITLE
Long, cramped tables

### ISSUE THREAD

**Issue by joshbaskaran** [fairtracks/fairtracks.net#26]
Opening as issue to collect opinions on UI/ alternative suggestions regarding the tables.

Current idea:
I modified the tables so that when we have certain columns (organisms and assays in this snapshot) with more than 1 element, the entire column gets replaced with 'Multiple' and the column details appear in a tooltip.

The good:
- Retains searching
- Looks much better

The bad:
- Needs per table adjustments/ some fancy abstraction.
This is mostly due to the fact that the table headers are different.

The ugly
- Code duplication between tables 😢 

![Screenshot 2022-05-10 at 13 59 59](https://user-images.githubusercontent.com/66942863/167623441-e91b1a1e-ab4e-476c-a7ba-6193d520152b.png)

**Comment by joshbaskaran** [comment]
- [x] Try vertical tooltip if possible
- [x] Add "i" to mark the presence of a tooltip 
- [x] refactor using a single slot component with dynamic manipulator
- [x] Make the species italic

**Comment by sveinugu** [comment]
Reading of tables from CSV files has now been implemented: https://github.com/fairtracks/fairtracks.net/commit/8f6b39498424145e503c065d2f5038bee1e5783c !

**Comment by joshbaskaran** [comment]
to do:
- [x] use the new datatable component to render all the csv tables.
