### ISSUE TITLE
.githubRepoInfo.json not being generated

### ISSUE THREAD

**Issue by joshbaskaran** [fairtracks/fairtracks.net#37]
Looks like this file is required for the website to run on the localhost.

Issue persisted through multiple node/ npm versions.
Git pull/ push were working fine without the fine.

The file was added to .pretrierignore during commit [69c5ce3](https://github.com/fairtracks/fairtracks.net/commit/69c5ce38dee91db3d4c340a4da21be8536c40e76)

Current solution: Obtain the file from someone else and keep it in project root.

**Comment by sveinugu** [comment]
You need to add a GitHub auth token to the `.env` file, e.g. :

```
FAIRTRACKS_GITHUB_AUTH_TOKEN = 'ghp_hereISmyTOKEN123'
OPTIMIZE_IMAGES_IN_DEV = false
```

Then the file should autogenerate. If you have an existing token there, it might have expired.

**Comment by sveinugu** [comment]
That being said (and if there is no other reason for the issue) this should be better documented and a fallback solution should be implemented, so we should keep this issue for that.

**Comment by bianchini88** [comment]
I do have a GitHub auth token, which I set up more than a year ago (it is set for not expiring) and I can push/pull from GitHub without any problem. The credential.helper is set to store, and the credentials are saved in the .git-credentials file. Is there anything in my setup which is not compatible with how things are supposed to be working?

**Comment by joshbaskaran** [comment]
> I do have a GitHub auth token, which I set up more than a year ago (it is set for not expiring) and I can push/pull from GitHub without any problem. The credential.helper is set to store, and the credentials are saved in the .git-credentials file. Is there anything in my setup which is not compatible with how things are supposed to be working?

You should be able to generate a new token (leaving the old one untouched) and just add the new one to the .env file.

**Comment by joshbaskaran** [comment]
> That being said (and if there is no other reason for the issue) this should be better documented and a fallback solution should be implemented, so we should keep this issue for that.

I agree, the repo shouldn't be coupled with github tokens especially since it's a public codebase. One should be able to simply clone/ fork and get it running even without a github account.
