### ISSUE TITLE
Problems with characters and hyperlinks in the metadata of markdown files

### ISSUE THREAD

**Issue by bianchini88** [fairtracks/fairtracks.net#53]
the character ":" seems to create issues when used in the metadata. The error is 
" incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line" 
Note that the character works fine if not followed by a space. 

Also, hyperlinks seem not to work correctly when used in the description, e.g. \[Genomic HyperBrowser](http://hyperbrowser.uio.no)
does not display correctly as [Genomic HyperBrowser](http://hyperbrowser.uio.no).

**Comment by sveinugu** [comment]
> the character ":" seems to create issues when used in the metadata. The error is " incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line" Note that the character works fine if not followed by a space.

I think this is a Markdown thing. Quoting the string should work. See https://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-colon-and-hyphen-in-yaml

> Also, hyperlinks seem not to work correctly when used in the description, e.g. [Genomic HyperBrowser](http://hyperbrowser.uio.no) does not display correctly as [Genomic HyperBrowser](http://hyperbrowser.uio.no).

This is easily fixed in components/ui/MaterialsCard.vue. However, I don't think it should have worked before either? In any case, I think we decided to scrap the description text anyway and instead use tags.

**Comment by bianchini88** [comment]
Using "title: > " instead of "title:" fixes it, thanks!

> I think we decided to scrap the description 

Shall I just delete the description from the cards, then? 
As it is now, the text gets truncated due to the size limit of the card and it does not look good.

**Comment by sveinugu** [comment]
> Using "title: > " instead of "title:" fixes it, thanks!
> 
> > I think we decided to scrap the description
> 
> Shall I just delete the description from the cards, then? As it is now, the text gets truncated due to the size limit of the card and it does not look good.

Yes, scrap them!

**Comment by bianchini88** [comment]
Descriptions deleted, closing the issue.
